[Sample] Fix new compilation warnings by gcc-9.2
Fix the new compilation warnings raised by gcc-9.2 in Yocto-3.

  apps/sample/sensorFramework/plugins/iioPlugin/iioPlugin.c:599:26: error:
    passing argument 1 to restrict-qualified parameter aliases with argument 4 [-Werror=restrict]
  599 |                 snprintf(resourcePath, sizeof(resourcePath), "%s/%s", resourcePath, "value");
      |                          ^~~~~~~~~~~~                                 ~~~~~~~~~~~~
  apps/sample/sensorFramework/plugins/iioPlugin/iioPlugin.c:599:66: error:
    ‘%s’ directive output may be truncated writing 5 bytes into a region of size between 0 and 255 [-Werror=format-truncation=]
  599 |                 snprintf(resourcePath, sizeof(resourcePath), "%s/%s", resourcePath, "value");
      |                                                                  ^~                 ~~~~~~~
  apps/sample/sensorFramework/plugins/iioPlugin/iioPlugin.c:599:17: note:
    ‘snprintf’ output between 7 and 262 bytes into a destination of size 256
  599 |                 snprintf(resourcePath, sizeof(resourcePath), "%s/%s", resourcePath, "value");
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

These warnings arise from using snprintf to modify the source buffer,
even though the standards clearly state that the result is undefined.

Resolves: LE-14521
Related: LE-14421
Change-Id: I51258774ec336d90ade6f386356f3bdd78dc64fe
Signed-off-by: Anju Kunjumon <akunjumon@sierrawireless.com>
(cherry picked from commit 0fcfbd08506bae92b41c48fee572c49c5beb03b0)